### ISSUE TITLE
Todo next release (5.11.3)

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/AutoPlug-Client#163]
- [x] FIX: Needing to press enter twice at the end of first setup
- [ ] FIX: Server jar path not getting encapsulated in quotes, which made autoplug unable to find the server jar if the path contained spaces.
- [ ] FIX: Fabric not getting detected for new fabric installations. (check fabric jar for install.properties (inside check for fabric string) and fabric.installer.json)
- [ ] FIX: First setup does not support creation of new servers
- [ ] FIX: Some mod details cannot be fetched.
![image](https://user-images.githubusercontent.com/59899645/163673031-16a7bd3e-0f31-4df2-92e2-3b4678c88039.png)
- [ ] NEW: AutoPlug now searches for other config files inside the jar to find missing information like author name. Before it would just check one config for all the data. This should result in less 
- [ ] NEW: Press enter to retry functionality at critical parts of initialisation, for easier configuration of AutoPlug.
